name: Nightly Ingest

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        python -m pip show pandas

    - name: Run ingest
      run: |
        python --version
        which python
        ls -R
        python src/ingest.py
